# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('number_of_contacts', models.IntegerField(default=0)),
            ],
        ),
    ]
